### ISSUE TITLE
Build and preview the production-ready app

### ISSUE THREAD

**Issue by ecocarlisle** [Inrupt-inc/generator-solid-angular#11]
Tried both npm run serve:dist and ng serve:dist and got errors.

**Comment by vleput** [comment]
I don't think that's an out of the box command for Angular projects: aren't you looking for `ng build --prod` instead?
Then you can preview that using [http-server](https://github.com/indexzero/http-server) for example

**Comment by james-martin-jd** [comment]
I think that @vleput is correct, according to [the docs](https://github.com/angular/angular-cli/wiki/serve), there's no serve:dist option. That sounds like a grunt setup or something similar to me, not angular-cli.

That same doc link above says you can add --prod to ng serve command, so "ng serve --prod" would likely be what you want.

**Comment by ecocarlisle** [comment]
I'll try that.  I appreciate the help.  I was following the Yeoman tutorial something that was hinted on in the Getting Started instructions for Solid.  With that generator you can preview the distribution locally with the following command: npm run serve:dist.  I assumed that this was something that was common throughout all the generators.
