### ISSUE TITLE
Generator not working

### ISSUE THREAD

**Issue by evmiguel** [Inrupt-inc/generator-solid-angular#21]
Hi, 

I am trying to create the sample Solid Angular application on my local machine, but the generator is not working. These are the steps I have followed:

1. `npm install -g @angular/cli`
2. `npm install -g yo`
3. `npm install -g @inrupt/generator-solid-angular`

This step `yo @inrupt/solid-angular` produces the following output:
```
Error @inrupt/solid-angular 

You don’t seem to have a generator with the name “@inrupt/solid-angular” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-@inrupt/solid-angular.

To see all your installed generators run yo without any arguments. Adding the --help option will also show subgenerators. 

If yo cannot find the generator, run yo doctor to troubleshoot your system.
```

Any help getting set up would be appreciated!

**Comment by james-martin-jd** [comment]
Closing this as there's been no response for some time. If this is still an issue, feel free to reopen it.
