### ISSUE TITLE
Loading Solid-Auth

### ISSUE THREAD

**Issue by willemneal** [Inrupt-inc/generator-solid-angular#3]
>13:58:20.372 localhost/:1 Failed to load https://solid.community/.well-known/openid-configuration: The 'Access-Control-Allow-Origin' header has a value '**https://localhost:4200'** that is not equal to the supplied origin. **Origin 'http://localhost:4200'** is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I assume I need to either change the header or get a cert, but shouldn't localhost be an exception?

**Comment by james-martin-jd** [comment]
@willemneal what were you trying to do when you received this error?

**Comment by willemneal** [comment]
After launching server I tried to sign in.

**Comment by james-martin-jd** [comment]
Interesting.. I don't see that same error locally. Which provider are you using to log in?

**Comment by willemneal** [comment]
Solid.community

On Oct 1, 2018 13:02, "James Martin" <notifications@github.com> wrote:

Interesting.. I don't see that same error locally. Which provider are you
using to log in?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Inrupt-inc/generator-solid-angular/issues/3#issuecomment-425984425>,
or mute the thread

**Comment by james-martin-jd** [comment]
I just tried installing this on a fresh box, and didn't see either of the errors you mentioned (CORS or otherwise), or any warnings either. Is there any other information you can provide so I can look into it?

I've tried it on MacOS and Windows 10 on Chrome. Looks like Edge/IE has some issues still but not the ones listed here.

**Comment by james-martin-jd** [comment]
Closing this as I do not plan to investigate this issue at the moment. Feel free to reopen if the issue persists.
